name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secrest.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrest.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrest.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrest.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrest.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrest.SECRET_KEY}}
      ALGORITHM: ${{secrest.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrest.ACCESS_TOKEN_EXPIRE_MINUTES}}
      TEST_DATABASE_NAME: ${{secrest.TEST_DATABASE_NAME}}
    runs-on: ubuntu-latest
    steps: 
      - name: pulling git repo 
        uses: actions/checkout@v2
      - name: Install python version 3.9  
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt  
      - name: test with pytest
        run: |
          pip install pytest
          pytest -vs      